[versions]

android-plugin = '8.11.1'

android-sdk-compile = '36'
android-sdk-min = '24'
android-sdk-target = '36'

java = '11'


[libraries]


[plugins]

android-application = { id = 'com.android.application', version.ref = 'android-plugin' }
